const domains = [
  { code:'01', key:'AI 모델', title:'AI 모델', desc:'LLM · 멀티모달 · 에이전트 · 오픈소스 생태계', score:92, level:'전략 이슈', color:'focus' },
  { code:'02', key:'AI 반도체', title:'AI 반도체', desc:'가속기 · HBM · 첨단 패키징 · 소프트웨어 생태계', score:88, level:'전략 이슈', color:'focus' },
  { code:'03', key:'네트워크·위성', title:'네트워크·위성', desc:'5G·6G · 위성통신 · 엣지 · 지상 통합망', score:76, level:'주요 동향', color:'keep' },
  { code:'04', key:'사이버보안·AI 안전', title:'사이버보안·AI 안전', desc:'AI 안전 · 공급망 · 양자내성암호 · 거버넌스', score:95, level:'긴급 이슈', color:'new' },
  { code:'05', key:'피지컬 AI', title:'피지컬 AI', desc:'휴머노이드 · 자율제조 · 자율주행', score:84, level:'전략 이슈', color:'focus' },
  { code:'06', key:'양자', title:'양자', desc:'컴퓨팅 · 통신 · 센서 · 내성암호', score:68, level:'주요 동향', color:'keep' },
  { code:'07', key:'BCI', title:'BCI', desc:'뇌신호 · 의료재활 · 인간증강 · 윤리', score:61, level:'관찰', color:'keep' }
];
const sources = [
  {name:'ITFind / IITP', org:'정보통신기획평가원', type:'정부·공공', domains:'전체 AI·ICT', method:'ITFind 주간 목록 점검 · 신규자료 매일 확인', url:'https://www.itfind.or.kr/'},
  {name:'NIST AI Risk Management Framework', org:'NIST', type:'정부·공공', domains:'사이버보안·AI 안전', method:'공식 웹페이지', url:'https://www.nist.gov/itl/ai-risk-management-framework'},
  {name:'NIST Post-Quantum Cryptography', org:'NIST', type:'정부·공공', domains:'양자 · 사이버보안·AI 안전', method:'공식 웹페이지', url:'https://www.nist.gov/pqc'},
  {name:'CISA Artificial Intelligence', org:'CISA', type:'정부·공공', domains:'사이버보안·AI 안전', method:'공식 웹페이지', url:'https://www.cisa.gov/ai'},
  {name:'OWASP Gen AI Security Project', org:'OWASP', type:'표준·전문기관', domains:'AI 모델 · 사이버보안·AI 안전', method:'공식 웹페이지', url:'https://genai.owasp.org/'},
  {name:'ETSI Non-Terrestrial Networks', org:'ETSI', type:'표준·전문기관', domains:'네트워크·위성', method:'공식 웹페이지', url:'https://www.etsi.org/newsroom/press-releases/2354-aiming-high-etsi-conference-on-non-terrestrial-networks-underlines-critical-role-of-ntn-in-realizing-tomorrow-s-global-6g-vision/'},
  {name:'NIST Quantum Information Science', org:'NIST', type:'정부·공공', domains:'양자', method:'공식 웹페이지', url:'https://www.nist.gov/quantum-information-science'},
  {name:'FDA/NIH Implanted BCI Workshop', org:'FDA · NIH', type:'정부·공공', domains:'BCI', method:'공식 행사·자료', url:'https://www.ninds.nih.gov/news-events/events/fda-nih-joint-workshop-developing-implanted-bci-clinical-outcome-assessments'},
  {name:'NVIDIA Research ASPIRE', org:'NVIDIA Research', type:'기업·연구', domains:'피지컬 AI', method:'공식 연구 페이지', url:'https://research.nvidia.com/labs/avg/'},
  {name:'Siemens Physical AI Factory', org:'Siemens', type:'기업 공식', domains:'피지컬 AI · 자율제조', method:'공식 보도자료', url:'https://press.siemens.com/global/en/pressrelease/siemens-and-humanoid-bring-physical-ai-factory-floor-deploying-humanoids-industrial'},
  {name:'Hugging Face Blog', org:'Hugging Face', type:'기업·커뮤니티', domains:'AI 모델', method:'공식 블로그', url:'https://huggingface.co/blog'},
  {name:'McKinsey Technology Trends', org:'McKinsey', type:'컨설팅·시장', domains:'전체 AI·ICT', method:'공식 리포트 페이지', url:'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights'},
  {name:'BCG Technology, Media & Telecom', org:'BCG', type:'컨설팅·시장', domains:'전체 AI·ICT', method:'공식 인사이트', url:'https://www.bcg.com/publications/industries/technology-media-telecommunications'},
  {name:'Gartner Emerging Technology', org:'Gartner', type:'시장조사', domains:'전체 AI·ICT', method:'공식 리서치 페이지', url:'https://www.gartner.com/en/research'},
  {name:'기술 리더·전문가 공개 채널', org:'X · LinkedIn · YouTube · Instagram · 개인 블로그', type:'전문가·SNS', domains:'전체 AI·ICT', method:'별도 감시 목록 · 미확인 신호로 검증', url:'https://www.linkedin.com/'}
];
const defaultPriorities = [
  {text:'AI 안전 국제규범과 평가체계', type:'강조', scope:'사이버보안·AI 안전', persistent:true},
  {text:'양자내성암호 전환 동향', type:'필수 포함', scope:'양자', persistent:true},
  {text:'단순 제품 업데이트', type:'비중 축소', scope:'전체', persistent:true}
];
let state = { view:'overview', filter:'전체', focused:null, clean:false, priorities:JSON.parse(localStorage.getItem('priorities') || 'null') || defaultPriorities, reportDoc:'design', reportEdits:JSON.parse(localStorage.getItem('reportEdits') || '{}') };
const reportFiles = { design:'/documents/ai-ict-strategy-design.md', semiconductor:'/documents/ai-semiconductor-sample.md', 'AI 모델':'/documents/report-ai-model.md', 'AI 반도체':'/documents/report-ai-semiconductor.md', '네트워크·위성':'/documents/report-network-satellite.md', '사이버보안·AI 안전':'/documents/report-cyber-ai-safety.md', '피지컬 AI':'/documents/report-physical-ai.md', '양자':'/documents/report-quantum.md', 'BCI':'/documents/report-bci.md' };
const $ = (s) => document.querySelector(s);
const toast = (msg) => { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2300); };
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('priorities',JSON.stringify(state.priorities));}
function tag(type){const cls=type==='긴급 이슈'?'new':type==='战略 이슈'?'focus':type==='전략 이슈'?'focus':'keep';return `<span class="status-tag ${cls}">${esc(type)}</span>`}
function renderOverview(){
  return `<div class="metric-grid">
    <div class="metric-card"><span class="label">추적 기술분야</span><strong>7</strong><small>피지컬 AI 3개 세부축 포함</small></div>
    <div class="metric-card"><span class="label">이번 주 주요 신호</span><strong>24</strong><small>지난주 대비 +6건</small></div>
    <div class="metric-card"><span class="label">전략 이슈</span><strong>08</strong><small class="warn">정책 검토 필요 3건</small></div>
    <div class="metric-card"><span class="label">지속 우선순위</span><strong>${state.priorities.length}</strong><small>사용자 지정 · 해제 전 유지</small></div>
  </div>
  <div class="section-label"><h2>이번 주의 판단 지형</h2><small>기술적 파급력 · 국가전략 관련성 · 시급성</small></div>
  <div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>분야별 전략 신호</h3><small>기준일 2026.09.16</small></div>${domains.slice(0,5).map(d=>`<div class="trend-row"><div class="trend-name">${d.title}</div><div><div class="trend-desc">${d.desc}</div><div class="bar"><i style="width:${d.score}%"></i></div></div><div class="trend-score">${d.score} / 100</div></div>`).join('')}</div>
  <div class="panel"><div class="panel-head"><h3>지금 읽어야 할 신호</h3><small>자동 선별</small></div><div class="signal-list"><div class="signal"><div><b>AI 안전은 보안의 하위 항목이 아니다</b><p>평가·거버넌스·오용 대응을 독립 정책축으로 유지해야 함</p></div></div><div class="signal positive"><div><b>피지컬 AI의 시장진입 경로가 구체화</b><p>휴머노이드·자율제조·자율주행을 분리해 실증 수요를 추적</p></div></div><div class="signal"><div><b>양자내성암호 전환 시점 재검토</b><p>표준·조달·공공 인프라의 연계 여부가 핵심 변수</p></div></div></div></div></div>
  <div class="section-label"><h2>누적 전략 업데이트</h2><small>변경표시 버전 · 최신 3건</small></div>${reports(true)}
  <div class="section-label"><h2>기술분야 바로가기</h2><button class="filter-btn" data-action="domains">전체 보기 →</button></div><div class="domain-grid">${domains.slice(0,4).map(domainCard).join('')}</div>`;
}
function reports(withTags=false){const items=[['09.16','AI 안전·보안','AI 안전성·정렬·평가를 사이버보안과 분리한 전략축으로 유지','강화'],['09.15','AI 반도체','정부 실증과 수요기업 공동투자 조건을 결합','수정'],['09.12','피지컬 AI','자율제조를 휴머노이드·자율주행과 별도 분석 단위로 고정','유지']];return items.map((r,i)=>`<div class="report-card"><div class="report-date"><strong>2026.${r[0]}</strong> WEEK ${36-i}</div><div class="report-body"><strong>${r[1]}</strong><p>${state.clean?'최신 판단: ':r[3]+' · '}${r[2]}</p></div>${state.clean?'':`<span class="status-tag ${r[3]==='수정'?'new':r[3]==='강화'?'focus':'keep'}">${r[3]}</span>`}</div>`).join('');}
function domainCard(d){return `<article class="domain-card ${state.focused===d.key?'focused':''}" data-domain="${esc(d.key)}"><div class="domain-top"><span class="domain-code">${d.code} / 07</span>${tag(d.level)}</div><h3>${d.title}</h3><p>${d.desc}</p><div class="domain-footer"><span>전략 신호</span><b>${d.score}</b></div></article>`}
function renderDomains(){const filtered=state.filter==='전체'?domains:domains.filter(d=>d.level===state.filter);return `<div class="panel"><div class="panel-head"><div><h3>기술분야별 동향리포트</h3><small>매주 독립 리포트 · 정책결정자용 요약 + 상세분석</small></div><div class="control-row">${['전체','긴급 이슈','전략 이슈','주요 동향','관찰'].map(f=>`<button class="filter-btn ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div></div><div class="domain-grid">${filtered.map(domainCard).join('')}</div></div><div class="section-label"><h2>${state.focused?state.focused+' 리포트 미리보기':'최근 리포트'}</h2><div class="control-row"><button class="filter-btn ${!state.clean?'active':''}" data-mode="tracked">변경표시</button><button class="filter-btn ${state.clean?'active':''}" data-mode="clean">정리본</button></div></div>${reports()}</div>`}
function renderStrategy(){return `<div class="panel"><div class="panel-head"><div><h3>누적형 전략 업데이트</h3><small>전주 기준선 위에 현재 판단을 쌓습니다</small></div><div class="control-row"><button class="filter-btn ${!state.clean?'active':''}" data-mode="tracked">분석·검토용</button><button class="filter-btn ${state.clean?'active':''}" data-mode="clean">배포·열람용</button></div></div>${state.clean?'<div class="empty" style="margin-bottom:12px">변경표시를 제거한 최신 판단본입니다. 근거와 출처는 유지됩니다.</div>':''}${reports()}</div><div class="section-label"><h2>변경 상태 정의</h2></div><div class="source-grid">${[['유지','기존 판단이 여전히 유효함','keep'],['수정','전제나 실행방안을 변경함','new'],['강화','우선순위나 규모를 높임','focus'],['비중 축소','본문 분량과 요약 비중을 줄임','keep']].map(x=>`<div class="source-card"><div><h3>${x[0]}</h3><p>${x[1]}</p></div>${tag(x[0])}</div>`).join('')}</div>`}
function renderSources(){return `<div class="panel"><div class="panel-head"><div><h3>소스 레지스트리</h3><small>실제 확인 가능한 기본 출처 ${sources.length}개 · 공식 링크를 열어 원문 확인</small></div><div class="control-row"><button class="filter-btn active" data-source-filter="전체">전체</button><button class="filter-btn" data-source-filter="정부·공공">정부·공공</button><button class="filter-btn" data-source-filter="기업·연구">기업·연구</button><button class="filter-btn" data-source-filter="컨설팅·시장">컨설팅·시장</button></div></div><div class="source-table"><div class="source-table-head"><span>소스</span><span>분류</span><span>적용 분야</span><span>수집 방식</span><span>원문</span></div>${sources.map((s,i)=>`<div class="source-table-row" data-source-type="${esc(s.type)}"><div><strong>${esc(s.name)}</strong><small>${esc(s.org)}</small></div><span class="source-pill">${esc(s.type)}</span><span>${esc(s.domains)}</span><span>${esc(s.method)}</span><a class="source-link" href="${esc(s.url)}" target="_blank" rel="noreferrer">열기 ↗</a></div>`).join('')}</div></div><div class="section-label"><h2>자료 수집·검증 규칙</h2><small>기준일 2026.09.23</small></div><div class="source-grid"><div class="source-card"><div><h3>핵심 근거</h3><p>ITFind·정부·공공기관·기업 공식자료·학술·기술자료를 우선 사용합니다.</p></div><span class="source-pill">우선</span></div><div class="source-card"><div><h3>보조 근거</h3><p>컨설팅·시장자료와 전문가·SNS는 초기 신호로 사용하고 복수 출처로 교차검증합니다.</p></div><span class="source-pill">검증</span></div></div>`}
function renderPriorities(){return `<div class="panel"><div class="panel-head"><div><h3>사용자 우선순위</h3><small>해제하거나 변경하기 전까지 모든 누적 보고서에 적용</small></div><button class="primary-btn" id="add-priority">+ 항목 추가</button></div><div class="priority-list">${state.priorities.length?state.priorities.map((p,i)=>`<div class="priority-item"><div><strong>${p.text}</strong><small>${p.scope} · ${p.type} · 지속 적용</small></div><div class="priority-actions"><button class="mini-btn" data-edit="${i}">수정</button><button class="mini-btn" data-remove="${i}">해제</button></div></div>`).join(''):'<div class="empty">지정된 우선순위가 없습니다.</div>'}</div></div>`}
function renderReportMarkdown(md){const lines=md.split(/\r?\n/);let html='',inList=false,inCode=false;for(const raw of lines){const line=raw.trimEnd();if(line.startsWith('```')){if(inCode){html+='</code></pre>';inCode=false}else{html+='<pre><code>';inCode=true}continue}if(inCode){html+=esc(line)+'\n';continue}if(!line.trim()){if(inList){html+='</ul>';inList=false}continue}if(line.startsWith('# ')){html+=`<h1>${esc(line.slice(2))}</h1>`}else if(line.startsWith('## ')){html+=`<h2>${esc(line.slice(3))}</h2>`}else if(line.startsWith('### ')){html+=`<h3>${esc(line.slice(4))}</h3>`}else if(line.startsWith('#### ')){html+=`<h4>${esc(line.slice(5))}</h4>`}else if(/^[-*] /.test(line)){if(!inList){html+='<ul>';inList=true}html+=`<li>${esc(line.slice(2))}</li>`}else if(/^\d+\. /.test(line)){if(!inList){html+='<ul>';inList=true}html+=`<li>${esc(line.replace(/^\d+\. /,''))}</li>`}else if(line.startsWith('> ')){html+=`<blockquote>${esc(line.slice(2))}</blockquote>`}else{html+=`<p>${esc(line)}</p>`}}if(inList)html+='</ul>';if(inCode)html+='</code></pre>';return html}
function renderReportsView(){return `<div class="report-workspace"><div class="report-library panel"><div class="panel-head"><div><h3>보고서 라이브러리</h3><small>설계문서·자료 기반·사용자 업로드</small></div><label class="upload-btn">+ Markdown 불러오기<input id="md-upload" type="file" accept=".md,.markdown,.txt" hidden></label></div><div class="library-list"><button class="library-item ${state.reportDoc==='design'?'selected':''}" data-report="design"><span class="file-icon">MD</span><span><b>AI·ICT 전략 분석 에이전트 구상안</b><small>인터뷰 확정본</small></span></button><button class="library-item ${state.reportDoc==='semiconductor'?'selected':''}" data-report="semiconductor"><span class="file-icon">MD</span><span><b>AI 반도체 일일동향 샘플</b><small>자료 기반 샘플</small></span></button>${domains.map(d=>`<button class="library-item ${state.reportDoc===d.key?'selected':''}" data-report="${esc(d.key)}"><span class="file-icon">${d.code}</span><span><b>${d.title} 분석 리포트</b><small>자료 기반 초기 리포트</small></span></button>`).join('')}${state.customDoc?`<button class="library-item selected" data-report="custom"><span class="file-icon">UP</span><span><b>${esc(state.customDoc.name)}</b><small>현재 세션 업로드</small></span></button>`:''}</div><div class="import-note">업로드 파일은 서버에 전송되지 않고 현재 브라우저 세션에서만 읽습니다.</div></div><div class="reader panel"><div class="reader-toolbar"><div><span class="eyebrow">SOURCE-BASED REPORT</span><h2 id="reader-title">문서를 불러오는 중…</h2></div><div class="control-row"><button class="filter-btn ${!state.clean?'active':''}" data-mode="tracked">분석·검토용</button><button class="filter-btn ${state.clean?'active':''}" data-mode="clean">정리본</button><button class="filter-btn" data-action="download">다운로드</button></div></div><div class="reader-meta" id="reader-meta">출처 기반 보고서를 불러오는 중입니다.</div><div id="edit-panel"></div><article class="markdown-body" id="doc-content"><div class="empty">문서를 불러오는 중입니다.</div></article></div></div>`}

function reportSections(md){return md.split(/\r?\n/).filter(line=>/^##? /.test(line)).map(line=>line.replace(/^##? /,'').trim()).filter(Boolean)}
function renderEditPanel(text){const sections=reportSections(text);const edits=state.reportEdits[state.reportDoc]||[];return `<div class="edit-request-panel"><div><b>이 보고서에 대한 편집 지시</b><small>이 보고서에만 적용되며, 해제 전까지 유지됩니다.</small></div><div class="edit-request-form"><select id="edit-section"><option value="">항목 선택</option>${sections.map(s=>`<option>${esc(s)}</option>`).join('')}</select><select id="edit-action"><option>필수 포함</option><option>강조</option><option>비중 축소</option><option>삭제 후보</option></select><input id="edit-reason" placeholder="이유 또는 요청사항"><button class="primary-btn" data-add-edit>저장</button></div>${edits.length?`<div class="edit-list">${edits.map((e,i)=>`<div class="edit-row"><span class="status-tag ${e.action==='강조'?'focus':e.action==='삭제 후보'?'new':'keep'}">${e.action}</span><strong>${esc(e.section)}</strong><small>${esc(e.reason||'사용자 요청')}</small><button class="mini-btn" data-remove-edit="${i}">해제</button></div>`).join('')}</div>`:'<div class="edit-empty">아직 이 보고서에 지정된 편집 지시가 없습니다.</div>'}</div>`}
async function loadReportDoc(){const content=$('#doc-content'),title=$('#reader-title'),meta=$('#reader-meta');if(!content)return;let name='';let text='';try{if(state.reportDoc==='custom'&&state.customDoc){name=state.customDoc.name;text=state.customDoc.text}else{const url=reportFiles[state.reportDoc]||reportFiles.design;const res=await fetch(url);if(!res.ok)throw new Error(`HTTP ${res.status}`);text=await res.text();const reportNames={design:'AI·ICT 전략 분석 에이전트 구상안',semiconductor:'AI 반도체 일일동향 샘플','AI 모델':'AI 모델 분석 리포트','AI 반도체':'AI 반도체 분석 리포트','네트워크·위성':'네트워크·위성 분석 리포트','사이버보안·AI 안전':'사이버보안·AI 안전 분석 리포트','피지컬 AI':'피지컬 AI 분석 리포트','양자':'양자 분석 리포트','BCI':'BCI 분석 리포트'};name=reportNames[state.reportDoc]||'분야별 분석 리포트'}title.textContent=name;meta.textContent=`${text.split(/\r?\n/).length}줄 · ${state.clean?'정리본 보기':'원문·변경추적 기준본 보기'}`;content.innerHTML=renderReportMarkdown(text);const related=sources.filter(s=>s.domains.includes(state.reportDoc)||s.domains==='전체 AI·ICT').slice(0,6);content.innerHTML+=`<section class="report-citations"><h2>이번 보고서의 실제 출처</h2><p>보고서 생성 기준일: 2026-09-23 · 아래 공개 원문을 기반으로 작성·검토합니다.</p><ul>${related.map(s=>`<li><a href="${s.url}" target="_blank" rel="noreferrer">${esc(s.name)} — ${esc(s.org)}</a></li>`).join('')}</ul></section>`;$('#edit-panel').innerHTML=renderEditPanel(text);bind()}catch(err){title.textContent='문서를 불러오지 못했습니다';meta.textContent='파일 경로 또는 형식을 확인하세요.';content.innerHTML=`<div class="empty">${esc(err.message)}<br><small>왼쪽에서 Markdown 파일을 직접 불러올 수 있습니다.</small></div>`}}
function render(){const labels={overview:'전체 상황판',domains:'기술분야 리포트',reports:'보고서 열람',strategy:'전략 업데이트',sources:'소스 레지스트리',priorities:'사용자 우선순위'};const titles={overview:'이번 주, 무엇이 바뀌었나',domains:'기술분야별 동향리포트',reports:'보고서를 직접 읽고 편집하다',strategy:'판단의 변화가 쌓이는 곳',sources:'무엇을 어디서 가져오는가',priorities:'중요한 것은 계속 남긴다'};const subtitles={overview:'AI·ICT 기술동향을 정책 판단과 실행방안으로 연결하는 누적형 워크스페이스',domains:'AI 모델부터 BCI까지, 동일한 분석체계로 비교합니다',reports:'기존 Markdown 문서와 업로드 자료를 브라우저에서 바로 열람합니다',strategy:'변경 사유를 보존한 분석본과 읽기 쉬운 정리본을 함께 관리합니다',sources:'ITFind를 중심으로 공식자료와 초기 신호를 분리 관리합니다',priorities:'사용자 판단은 자동 중요도 평가보다 우선합니다'};$('#view-label').textContent=labels[state.view];$('#page-title').textContent=titles[state.view];$('#page-subtitle').textContent=subtitles[state.view];$('#app-view').innerHTML=state.view==='overview'?renderOverview():state.view==='domains'?renderDomains():state.view==='reports'?renderReportsView():state.view==='strategy'?renderStrategy():state.view==='sources'?renderSources():renderPriorities();bind();if(state.view==='reports')loadReportDoc();}
function openPriority(prefill=''){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><h2>우선순위 지정</h2><p>이 지시는 해제하거나 변경할 때까지 관련 누적 보고서에 계속 적용됩니다.</p><label for="priority-text">대상 이슈</label><input id="priority-text" value="${esc(prefill)}" placeholder="예: 양자내성암호 관련 국내외 정책 변화"><label for="priority-type">편집 지시</label><select id="priority-type"><option>필수 포함</option><option>강조</option><option>비중 축소</option><option>삭제 후보</option></select><label for="priority-scope">적용 분야</label><input id="priority-scope" value="전체" placeholder="전체 또는 특정 기술분야"><div class="modal-actions"><button class="secondary-btn" data-close>취소</button><button class="primary-btn" data-save-priority>저장</button></div></div>`;document.body.append(wrap);wrap.querySelector('[data-close]').onclick=()=>wrap.remove();wrap.querySelector('[data-save-priority]').onclick=()=>{const text=$('#priority-text').value.trim();if(!text){toast('대상 이슈를 입력해 주세요.');return}state.priorities.unshift({text,type:$('#priority-type').value,scope:$('#priority-scope').value.trim()||'전체',persistent:true});save();wrap.remove();render();toast('지속 우선순위에 반영했습니다.');};}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.focused=null;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.clean=b.dataset.mode==='clean';render()});document.querySelectorAll('[data-domain]').forEach(c=>c.onclick=()=>{state.focused=c.dataset.domain;state.reportDoc=c.dataset.domain;state.view='reports';render();});document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{state.reportDoc=b.dataset.report;render()});document.querySelectorAll('[data-source-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-source-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[data-source-type]').forEach(row=>row.style.display=b.dataset.sourceFilter==='전체'||row.dataset.sourceType===b.dataset.sourceFilter?'grid':'none')});const addEdit=$('[data-add-edit]');if(addEdit)addEdit.onclick=()=>{const section=$('#edit-section').value;if(!section){toast('보고서 항목을 선택해 주세요.');return}const edit={section,action:$('#edit-action').value,reason:$('#edit-reason').value.trim()};if(!state.reportEdits[state.reportDoc])state.reportEdits[state.reportDoc]=[];state.reportEdits[state.reportDoc].push(edit);localStorage.setItem('reportEdits',JSON.stringify(state.reportEdits));render();toast('이 보고서의 편집 지시로 저장했습니다.');};document.querySelectorAll('[data-remove-edit]').forEach(b=>b.onclick=()=>{state.reportEdits[state.reportDoc].splice(Number(b.dataset.removeEdit),1);localStorage.setItem('reportEdits',JSON.stringify(state.reportEdits));render();toast('보고서 편집 지시를 해제했습니다.');});document.querySelectorAll('[data-action="domains"]').forEach(b=>b.onclick=()=>{state.view='domains';render()});document.querySelectorAll('[data-action="recommend"]').forEach(b=>b.onclick=()=>toast('추천 채널 6개를 검토 목록에 추가했습니다. 자동 등록하지 않았습니다.'));document.querySelectorAll('[data-action="download"]').forEach(b=>b.onclick=()=>{const text=state.reportDoc==='custom'&&state.customDoc?state.customDoc.text:'';if(!text){toast('현재 문서를 다운로드하려면 파일을 먼저 불러오세요.');return}const blob=new Blob([text],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.customDoc.name;a.click();URL.revokeObjectURL(a.href)});const upload=$('#md-upload');if(upload)upload.onchange=async()=>{const file=upload.files?.[0];if(!file)return;state.customDoc={name:file.name,text:await file.text()};state.reportDoc='custom';render();toast('Markdown 파일을 현재 세션에 불러왔습니다.');};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.priorities.splice(Number(b.dataset.remove),1);save();render();toast('우선순위를 해제했습니다.');});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openPriority(state.priorities[Number(b.dataset.edit)].text));const add=$('#add-priority');if(add)add.onclick=()=>openPriority();}
$('#new-priority').onclick=()=>openPriority();$('#focus-btn').onclick=()=>{$('#focus-btn').classList.toggle('active');toast('핵심 신호 보기 설정을 전환했습니다.');};render();
