const domains = [
  { code:'01', key:'AI 모델', title:'AI 모델', desc:'LLM · 멀티모달 · 에이전트 · 오픈소스 생태계', score:92, level:'전략 이슈', color:'focus' },
  { code:'02', key:'AI 반도체', title:'AI 반도체', desc:'가속기 · HBM · 첨단 패키징 · 소프트웨어 생태계', score:88, level:'전략 이슈', color:'focus' },
  { code:'03', key:'네트워크·위성', title:'네트워크·위성', desc:'5G·6G · 위성통신 · 엣지 · 지상 통합망', score:76, level:'주요 동향', color:'keep' },
  { code:'04', key:'사이버보안·AI 안전', title:'사이버보안·AI 안전', desc:'AI 안전 · 공급망 · 양자내성암호 · 거버넌스', score:95, level:'긴급 이슈', color:'new' },
  { code:'05', key:'피지컬 AI', title:'피지컬 AI', desc:'휴머노이드 · 자율제조 · 자율주행', score:84, level:'전략 이슈', color:'focus' },
  { code:'06', key:'양자', title:'양자', desc:'컴퓨팅 · 통신 · 센서 · 내성암호', score:68, level:'주요 동향', color:'keep' },
  { code:'07', key:'BCI', title:'BCI', desc:'뇌신호 · 의료재활 · 인간증강 · 윤리', score:61, level:'관찰', color:'keep' }
];
const sources = [
  ['ITFind 연계 기관','IITP ITFind 등록·연계 기관 전체','핵심 근거 · 매일 수집 / 매주 목록 점검','핵심'],
  ['정부·공공기관','국내외 정부·규제·표준·국제기구','정책·예산·규제·인재육성 원자료','핵심'],
  ['기업 공식 자료','빅테크·국내외 기업·오픈소스','기술발표·제품·실적·릴리스·백서','핵심'],
  ['학술·기술 자료','논문·특허·학회·벤치마크','기술수준·성능·실증·원천성 검증','핵심'],
  ['시장·산업·컨설팅','McKinsey·BCG·Bain·Gartner·IDC 등','시장전망·산업구도·투자 흐름','보조'],
  ['전문가·SNS','기술 리더·블로거·X·LinkedIn·YouTube·Instagram','초기 신호·현장 관찰·전문가 관점','보조'],
  ['뉴스·전문 미디어','국내외 언론·AI·ICT 전문매체','사건 탐지·시장 반응·맥락 파악','보조']
];
const defaultPriorities = [
  {text:'AI 안전 국제규범과 평가체계', type:'강조', scope:'사이버보안·AI 안전', persistent:true},
  {text:'양자내성암호 전환 동향', type:'필수 포함', scope:'양자', persistent:true},
  {text:'단순 제품 업데이트', type:'비중 축소', scope:'전체', persistent:true}
];
let state = { view:'overview', filter:'전체', focused:null, clean:false, priorities:JSON.parse(localStorage.getItem('priorities') || 'null') || defaultPriorities };
const $ = (s) => document.querySelector(s);
const toast = (msg) => { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2300); };
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('priorities',JSON.stringify(state.priorities));}
function tag(type){const cls=type==='긴급 이슈'?'new':type==='战略 이슈'?'focus':type==='전략 이슈'?'focus':'keep';return `<span class="status-tag ${cls}">${esc(type)}</span>`}
function renderOverview(){
  return `<div class="metric-grid">
    <div class="metric-card"><span class="label">추적 기술분야</span><strong>7</strong><small>피지컬 AI 3개 세부축 포함</small></div>
    <div class="metric-card"><span class="label">이번 주 주요 신호</span><strong>24</strong><small>지난주 대비 +6건</small></div>
    <div class="metric-card"><span class="label">전략 이슈</span><strong>08</strong><small class="warn">정책 검토 필요 3건</small></div>
    <div class="metric-card"><span class="label">지속 우선순위</span><strong>${state.priorities.length}</strong><small>사용자 지정 · 해제 전 유지</small></div>
  </div>
  <div class="section-label"><h2>이번 주의 판단 지형</h2><small>기술적 파급력 · 국가전략 관련성 · 시급성</small></div>
  <div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>분야별 전략 신호</h3><small>기준일 2026.09.16</small></div>${domains.slice(0,5).map(d=>`<div class="trend-row"><div class="trend-name">${d.title}</div><div><div class="trend-desc">${d.desc}</div><div class="bar"><i style="width:${d.score}%"></i></div></div><div class="trend-score">${d.score} / 100</div></div>`).join('')}</div>
  <div class="panel"><div class="panel-head"><h3>지금 읽어야 할 신호</h3><small>자동 선별</small></div><div class="signal-list"><div class="signal"><div><b>AI 안전은 보안의 하위 항목이 아니다</b><p>평가·거버넌스·오용 대응을 독립 정책축으로 유지해야 함</p></div></div><div class="signal positive"><div><b>피지컬 AI의 시장진입 경로가 구체화</b><p>휴머노이드·자율제조·자율주행을 분리해 실증 수요를 추적</p></div></div><div class="signal"><div><b>양자내성암호 전환 시점 재검토</b><p>표준·조달·공공 인프라의 연계 여부가 핵심 변수</p></div></div></div></div></div>
  <div class="section-label"><h2>누적 전략 업데이트</h2><small>변경표시 버전 · 최신 3건</small></div>${reports(true)}
  <div class="section-label"><h2>기술분야 바로가기</h2><button class="filter-btn" data-action="domains">전체 보기 →</button></div><div class="domain-grid">${domains.slice(0,4).map(domainCard).join('')}</div>`;
}
function reports(withTags=false){const items=[['09.16','AI 안전·보안','AI 안전성·정렬·평가를 사이버보안과 분리한 전략축으로 유지','강화'],['09.15','AI 반도체','정부 실증과 수요기업 공동투자 조건을 결합','수정'],['09.12','피지컬 AI','자율제조를 휴머노이드·자율주행과 별도 분석 단위로 고정','유지']];return items.map((r,i)=>`<div class="report-card"><div class="report-date"><strong>2026.${r[0]}</strong> WEEK ${36-i}</div><div class="report-body"><strong>${r[1]}</strong><p>${state.clean?'최신 판단: ':r[3]+' · '}${r[2]}</p></div>${state.clean?'':`<span class="status-tag ${r[3]==='수정'?'new':r[3]==='강화'?'focus':'keep'}">${r[3]}</span>`}</div>`).join('');}
function domainCard(d){return `<article class="domain-card ${state.focused===d.key?'focused':''}" data-domain="${esc(d.key)}"><div class="domain-top"><span class="domain-code">${d.code} / 07</span>${tag(d.level)}</div><h3>${d.title}</h3><p>${d.desc}</p><div class="domain-footer"><span>전략 신호</span><b>${d.score}</b></div></article>`}
function renderDomains(){const filtered=state.filter==='전체'?domains:domains.filter(d=>d.level===state.filter);return `<div class="panel"><div class="panel-head"><div><h3>기술분야별 동향리포트</h3><small>매주 독립 리포트 · 정책결정자용 요약 + 상세분석</small></div><div class="control-row">${['전체','긴급 이슈','전략 이슈','주요 동향','관찰'].map(f=>`<button class="filter-btn ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div></div><div class="domain-grid">${filtered.map(domainCard).join('')}</div></div><div class="section-label"><h2>${state.focused?state.focused+' 리포트 미리보기':'최근 리포트'}</h2><div class="control-row"><button class="filter-btn ${!state.clean?'active':''}" data-mode="tracked">변경표시</button><button class="filter-btn ${state.clean?'active':''}" data-mode="clean">정리본</button></div></div>${reports()}</div>`}
function renderStrategy(){return `<div class="panel"><div class="panel-head"><div><h3>누적형 전략 업데이트</h3><small>전주 기준선 위에 현재 판단을 쌓습니다</small></div><div class="control-row"><button class="filter-btn ${!state.clean?'active':''}" data-mode="tracked">분석·검토용</button><button class="filter-btn ${state.clean?'active':''}" data-mode="clean">배포·열람용</button></div></div>${state.clean?'<div class="empty" style="margin-bottom:12px">변경표시를 제거한 최신 판단본입니다. 근거와 출처는 유지됩니다.</div>':''}${reports()}</div><div class="section-label"><h2>변경 상태 정의</h2></div><div class="source-grid">${[['유지','기존 판단이 여전히 유효함','keep'],['수정','전제나 실행방안을 변경함','new'],['강화','우선순위나 규모를 높임','focus'],['비중 축소','본문 분량과 요약 비중을 줄임','keep']].map(x=>`<div class="source-card"><div><h3>${x[0]}</h3><p>${x[1]}</p></div>${tag(x[0])}</div>`).join('')}</div>`}
function renderSources(){return `<div class="panel"><div class="panel-head"><div><h3>소스 레지스트리</h3><small>공식 피드·RSS·Open API 우선 · SNS는 별도 감시 목록</small></div><button class="primary-btn" data-action="recommend">추천 채널 검토</button></div><div class="source-grid">${sources.map(s=>`<div class="source-card"><div><h3>${s[0]}</h3><p>${s[1]}<br>${s[2]}</p></div><span class="source-pill">${s[3]}</span></div>`).join('')}</div></div><div class="section-label"><h2>수집 운영 규칙</h2></div><div class="panel"><div class="signal-list"><div class="signal positive"><div><b>매일</b><p>기관별 신규·업데이트 자료를 확인하고 기술분야별 DB에 반영</p></div></div><div class="signal positive"><div><b>매주</b><p>ITFind 연계 기관 목록과 연결·제공 상태 점검</p></div></div><div class="signal"><div><b>검증</b><p>중요 사실은 복수 출처로 교차검증하고 미확인 SNS는 미확인 신호로 표시</p></div></div></div></div>`}
function renderPriorities(){return `<div class="panel"><div class="panel-head"><div><h3>사용자 우선순위</h3><small>해제하거나 변경하기 전까지 모든 누적 보고서에 적용</small></div><button class="primary-btn" id="add-priority">+ 항목 추가</button></div><div class="priority-list">${state.priorities.length?state.priorities.map((p,i)=>`<div class="priority-item"><div><strong>${p.text}</strong><small>${p.scope} · ${p.type} · 지속 적용</small></div><div class="priority-actions"><button class="mini-btn" data-edit="${i}">수정</button><button class="mini-btn" data-remove="${i}">해제</button></div></div>`).join(''):'<div class="empty">지정된 우선순위가 없습니다.</div>'}</div></div>`}
function render(){const labels={overview:'전체 상황판',domains:'기술분야 리포트',strategy:'전략 업데이트',sources:'소스 레지스트리',priorities:'사용자 우선순위'};const titles={overview:'이번 주, 무엇이 바뀌었나',domains:'기술분야별 동향리포트',strategy:'판단의 변화가 쌓이는 곳',sources:'무엇을 어디서 가져오는가',priorities:'중요한 것은 계속 남긴다'};const subtitles={overview:'AI·ICT 기술동향을 정책 판단과 실행방안으로 연결하는 누적형 워크스페이스',domains:'AI 모델부터 BCI까지, 동일한 분석체계로 비교합니다',strategy:'변경 사유를 보존한 분석본과 읽기 쉬운 정리본을 함께 관리합니다',sources:'ITFind를 중심으로 공식자료와 초기 신호를 분리 관리합니다',priorities:'사용자 판단은 자동 중요도 평가보다 우선합니다'};$('#view-label').textContent=labels[state.view];$('#page-title').textContent=titles[state.view];$('#page-subtitle').textContent=subtitles[state.view];$('#app-view').innerHTML=state.view==='overview'?renderOverview():state.view==='domains'?renderDomains():state.view==='strategy'?renderStrategy():state.view==='sources'?renderSources():renderPriorities();bind();}
function openPriority(prefill=''){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><h2>우선순위 지정</h2><p>이 지시는 해제하거나 변경할 때까지 관련 누적 보고서에 계속 적용됩니다.</p><label for="priority-text">대상 이슈</label><input id="priority-text" value="${esc(prefill)}" placeholder="예: 양자내성암호 관련 국내외 정책 변화"><label for="priority-type">편집 지시</label><select id="priority-type"><option>필수 포함</option><option>강조</option><option>비중 축소</option><option>삭제 후보</option></select><label for="priority-scope">적용 분야</label><input id="priority-scope" value="전체" placeholder="전체 또는 특정 기술분야"><div class="modal-actions"><button class="secondary-btn" data-close>취소</button><button class="primary-btn" data-save-priority>저장</button></div></div>`;document.body.append(wrap);wrap.querySelector('[data-close]').onclick=()=>wrap.remove();wrap.querySelector('[data-save-priority]').onclick=()=>{const text=$('#priority-text').value.trim();if(!text){toast('대상 이슈를 입력해 주세요.');return}state.priorities.unshift({text,type:$('#priority-type').value,scope:$('#priority-scope').value.trim()||'전체',persistent:true});save();wrap.remove();render();toast('지속 우선순위에 반영했습니다.');};}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.focused=null;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.clean=b.dataset.mode==='clean';render()});document.querySelectorAll('[data-domain]').forEach(c=>c.onclick=()=>{state.focused=c.dataset.domain;state.view='domains';render();toast(`${c.dataset.domain} 분야를 선택했습니다.`)});document.querySelectorAll('[data-action="domains"]').forEach(b=>b.onclick=()=>{state.view='domains';render()});document.querySelectorAll('[data-action="recommend"]').forEach(b=>b.onclick=()=>toast('추천 채널 6개를 검토 목록에 추가했습니다. 자동 등록하지 않았습니다.'));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.priorities.splice(Number(b.dataset.remove),1);save();render();toast('우선순위를 해제했습니다.');});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openPriority(state.priorities[Number(b.dataset.edit)].text));const add=$('#add-priority');if(add)add.onclick=()=>openPriority();}
$('#new-priority').onclick=()=>openPriority();$('#focus-btn').onclick=()=>{$('#focus-btn').classList.toggle('active');toast('핵심 신호 보기 설정을 전환했습니다.');};render();
